CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, username TEXT NOT NULL UNIQUE, passwd TEXT NOT NULL, register_data TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE log (id INTEGER PRIMARY KEY AUTOINCREMENT, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, msg TEXT NOT NULL);
