CREATE TABLE users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, passwd TEXT NOT NULL, confirmed INTEGER DEFAULT 0, register_data TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE log (id INTEGER PRIMARY KEY AUTOINCREMENT, date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, msg TEXT NOT NULL);
